### ISSUE TITLE
Upgrade MicroPython beta (on beta deployment only)

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-v3#1155]
We're expecting a MicroPython beta soon and we're going to do some of the upgrade work ahead of the beta being ready to get stubs changes prepped.

## New MicroPython releases

**Link new releases here**

Recent build from master for now.
Just aiming to use beta MicroPython on the staging/beta deployment.

## Todo

Simulator:

- [ ] Review changelogs and [diff](https://github.com/microbit-foundation/micropython-microbit-v2/compare/v2.1.2...master) to determine simulator changes, stubs changes any other documentation changes
- [ ] Raise educational content impact to Foundation education team (likely already in hand or low priority) 
- [ ] Update simulator as required
- [ ] Run through simulator examples in simulator demo.html
- [ ] Test simulator in Python Editor (locally)
- [ ] Merge simulator changes

Editor:

- [ ] Update stubs as required
- [ ] Update MicroPython hex files and version metadata in the editor
- [ ] PR with updated sim (via staging) and stubs
- [ ] Release stubs
- [ ] Test and merge PR

Now or later:

- [ ] Release simulator
- [ ] Update and publish simulator versioning CloudFront function
- [ ] Release editor

**Comment by microbit-matt-hillsdon** [comment]
There's been a few rounds of work on this as the MicroPython update approaches its first beta.

We're primarily waiting for tweaks/feedback re audio record and playback in MicroPython and some browser compatibility work re implementing that in the sim.

Work in progress links:
https://review-python-editor-v3.microbit.org/beta-micropython/
https://review-python-simulator.usermbit.org/beta-updates/demo.html

[Stubs PR](https://github.com/microbit-foundation/micropython-microbit-stubs/pull/97)

[Sim PR](https://github.com/microbit-foundation/micropython-microbit-v2-simulator/pull/113)
