### ISSUE TITLE
WebUSB interactions: connect/disconnect, flashing, serial

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-v3#13]
## Description

The prototype has WebUSB support based on the the v2 editor. 

This needs to be reviewed and update to provide at least as good a quality experience as the v2 editor.

## Todo

- [x] Collect input on the current implementation.
- [x] Review and test the existing code. Structure the testing with a view to extracting the code to a separate library in future.
- [x] Sync with recent changes in the v2 editor.
- [ ] Write or repurpose manual tests for scenarios that cannot be automated (e.g. unplugging the device).
- [ ] Bring UI for showing flashing progress, success and error handling up to a sufficient standard for MVP.
- [x] Reinstate the event / metrics tracking. The actual reporting can be via a stub to be tackled separately.
- [ ] Plan any future work
