### ISSUE TITLE
Code persistence across refresh

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-v3#17]
## Description

The prototype editor ~~has~~ had code persistence but it needs reconsidering and testing.

## Todo

- [x] Discuss trade-offs and multi-tab scenarios
- [x] Agree an approach for the MVP
    - Discussed with @microbit-carlos @microbit-giles and @daniasuheimat. We agreed that we'd go with a session-storage-only approach to avoid the complexities of other options which we documented on https://paper.dropbox.com/doc/Python-editor-V3-code-persistence--BIwME3lzfXwtQYVBw2STY5LkAg-vnbVcNeM9NRxJcAGxkiJO
 
- [x] Implement and test
    - [x] See if we can pull the version information we track into fs.ts rather than storage.ts. We don't need to persist it and it gets in the way.
    - [x] Implement sessionStorage using base64-js
    - [x] Give up when we hit errors, making sure we don't partially restore code (e.g. clear storage and swap in null impl)
    - [x] Test out performance and figure out how often we ought to call it. No option to use a worker so it's got to be quick enough.

Ensure we plan for multi-file scenarios.
