### ISSUE TITLE
Extract device connection code to a separate library

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-v3#18]
## Depends on

#13 

## Description

Extract the WebUSB code and associated tests to its own library. 

## Todo

- [ ] Review and generalise the interface. Get input from the micro:bit team.
- [ ] Split out and setup Git, CI etc. for separate project.
- [ ] Add documentation suitable for an external audience, including a vanilla JS demo.

**Comment by microbit-matt-hillsdon** [comment]
Please comment on this issue if this would be useful to you.

**Comment by microbit-matt-hillsdon** [comment]
This is available as https://github.com/microbit-foundation/microbit-connection/ for a while now.
