### ISSUE TITLE
Integration for Python Editor v3 in mobile apps

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/python-editor-v3#205]
## Depends on

Other tickets:

- [ ] https://github.com/microbit-foundation/microbit-ios/issues/61 (private)
- [ ] Android ticket to be raised once the news of the Python Editor v3 is public

Third parties:

- Insight resources for iOS app

## Description

We will want to support flashing the micro:bit V2 from the editor in our mobile apps. Some discussion around this has already taken place in https://github.com/microbit-foundation/v2/issues/830 (private). This ticket is to track the integration.

## Todo

- [ ] Update the Lets Code, mobile pages and Python Editor pages on microbit.org and support.microbit.org  to reflect the availability of the Python Editor in the apps
