### ISSUE TITLE
[i18n] Translation integration with Crowdin

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-v3#238]
## Depends on

Consensus as to the right time to make new Python editor content available for translation. Considerations include community translator availability, other translation priorities and the degree of translation churn as the editor is developed.

## Description

The V2 editor has community contributed translations via Micro:bit Educational Foundation's Crowdin project.

We should do likewise for V3.

We've laid the groundwork for this. The project uses react-intl with (hopefully!) all the messages extracted.

Previous testing demonstrated that the JSON files could be translated in Crowdin by transforming them slightly to correspond to the "Crome JSON" format. This just involves renaming the "defaultMessage" key to "message" on the way in and inverting the transform on the translated documents.

## Todo

- [ ] Scripts and perhaps CI jobs to update content in Crowdin
- [ ] Scripts to pull content from Crowdin in the required format for the app.
- [ ] Internal co-ordination.

Further discussion and work might be needed as we start to add more educational content into the editor as the same strings-based translation system may not be appropriate.

## Conclusion

...

**Comment by microbit-matt-hillsdon** [comment]
We have a process for this that is sufficient for now. CMS content is auto-synced by Foundation managed CI jobs. Pyright, stubs and UI strings are updated via a script that processes the Crowdin ZIPs. There is no automatic updating of that content in Crowdin, but I think I prefer a careful manual process with diff review so we're aware of the string churn we're causing.

Closing.
