### ISSUE TITLE
First release tasks

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-v3#28]
## Depends on

Other tickets:

- N/A

Third parties:

- N/A

## Todo

- [ ] Switch to production GA details
- [ ] Disable GA for staging
- [ ] Setup CF/DNS assuming we keep the same approach
- [ ] Double check Sentry settings + that we're happy to use it live
