### ISSUE TITLE
Add onbeforeunload handler to warn on quit with changes that haven't been downloaded

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-v3#43]
## Description

Add onbeforeunload handler to warn on quit with changes that haven't been downloaded.

We don't currently track when files have been changed ("dirty" in the old editor) but this should be easy to add in the file system code (fs.ts).

Check the situation in the real world. The text in the v2 editor is not used for me in Chrome.  I think Chrome substitutes a generic dialog to prevent sites misleading the user.

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

We could choose not to implement this if we're happy with how local storage or similar is working (not implemented as of now).

## Todo

- [ ] Understand the feature in the v2 Python editor - https://github.com/bbcmicrobit/PythonEditor/
- [ ] Review the file system code and come up with a plan for tracking whether we're dirty that's equivalent to the v2 editor (but nicer!)
- [ ] Add a listener somewhere appropriate
- [ ] See if we can e2e test this. Can we interact with the dialog via puppeteer? If we can then I suspect the v2 e2e tests will have an example.
